---

- name: Set EC2 metadata facts
  amazon.aws.ec2_metadata_facts:

- name: Set host facts for passwd database
  ansible.builtin.getent:
    database: passwd

- name: Check required variables are set
  ansible.builtin.assert:
    that:
      - environment_name is defined and environment_name | trim | length > 0
      - application_artifact_path is defined and application_artifact_path | trim | length > 0
    msg: "Required variable(s) empty or undefined"

- name: Check required variables are set
  ansible.builtin.assert:
    that:
      - tuxedo_service is defined and tuxedo_service | length > 0
      - environment_name is defined and environment_name | trim | length > 0
      - application_artifact_path is defined and application_artifact_path | trim | length > 0
      - application_configs_path is defined and application_configs_path | trim | length > 0
    msg: "Required variable(s) empty or undefined"

# The hostname is assumed to be in the format: ais-tuxedo-<environment>-<instance-index>
- name: Set common Tuxedo fact for domain suffix
  ansible.builtin.set_fact:
    tuxedo_common_suffix: "{{ ansible_facts.hostname
      | regex_replace('^ais-tuxedo-([A-Za-z]+)-(\\d+)$', '\\2_\\1')
      | upper }}"

- name: Set Tuxedo facts for config population
  ansible.builtin.set_fact:
    tuxedo_domain_id_suffix: "{{ tuxedo_common_suffix + '_DOM' }}"
    tuxedo_logical_machine_id_suffix: "{{ tuxedo_common_suffix + '_SRV' }}"
    tuxedo_local_domain_suffix: "{{ tuxedo_common_suffix + '_LOD' }}"

- name: Create rsyslog configuration
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart rsyslog service
    - Restart systemd-journald service

- name: Disable journal rate limiting
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    line: RateLimitBurst=0
  notify: Restart systemd-journald service

- name: Start rpcbind service
  ansible.builtin.systemd:
    name: rpcbind
    state: started
    enabled: true

- name: Set CloudWatch agent facts for config population
  ansible.builtin.set_fact:
    cloudwatch_agent: "{{ cloudwatch_agent_defaults | combine(cloudwatch_agent_overrides | default({})) }}"
    cloudwatch_log_stream_name: "{{ ansible_ec2_instance_id }}_{{ ansible_ec2_hostname }}"
    region: "{{ ansible_ec2_instance_identity_document_region }}"

- name: Create CloudWatch agent primary configuration file
  ansible.builtin.template:
    src: templates/cloudwatch-config.json.j2
    dest: "{{ cloudwatch_agent.config_dir }}/cloudwatch-config.json"
    owner: cwagent
    group: cwagent
    mode: '0644'
    trim_blocks: false

- name: Start CloudWatch agent using primary configuration file
  ansible.builtin.command:
    cmd: "{{ cloudwatch_agent.path }} -a fetch-config -m ec2 -s -c file:{{ cloudwatch_agent.config_dir }}/cloudwatch-config.json"
  changed_when: true

- name: Using constructed variable suffixes
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - tuxedo_domain_id_suffix
    - tuxedo_logical_machine_id_suffix
    - tuxedo_local_domain_suffix

- name: Create Tuxedo logs directory
  ansible.builtin.file:
    path: "{{ tuxedo_logs_path }}"
    owner: root
    group: "{{ tuxedo_service_group }}"
    mode: '0755'
    state: directory

- name: Create shared log rotation configuration for Tuxedo services
  ansible.builtin.template:
    src: templates/logrotate.tuxedo.conf.j2
    dest: "{{ tuxedo_log_rotation_config_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Configure cron jobs
  ansible.builtin.import_tasks: cron.yml

- name: Configure SELinux security contexts
  community.general.sefcontext:
    target: "{{ item.pattern }}"
    setype: "{{ item.type }}"
    ftype: "{{ item.ftype | default('a') }}"
    state: present
  loop:
    - pattern: "/opt/aws/amazon-cloudwatch-agent/logs(/.*)?"
      type: var_log_t
    - pattern: "/image/ais/logs(/.*)?"
      type: var_log_t
    - pattern: "/ais"
      type: var_log_t
      ftype: l
  register: selinux_contexts

- name: Apply SELinux security contexts recursively # noqa no-handler
  ansible.builtin.command: "restorecon -rv {{ item }}"
  loop:
    - /opt/aws/amazon-cloudwatch-agent/logs
    - /image/ais/logs
  when: selinux_contexts.changed
  changed_when: true

- name: Apply SELinux security contexts # noqa no-handler
  ansible.builtin.command: "restorecon -v {{ item }}"
  loop:
    - /ais
  when: selinux_contexts.changed
  changed_when: true

- name: Install additional tooling
  ansible.builtin.import_tasks: tools.yml

- name: Add host entry for SQL client connectivity
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1   {{ ansible_facts.hostname }}"

- name: Add dsr-batch public key to authorized_keys file
  ansible.posix.authorized_key:
    user: "{{ ais_user }}"
    state: present
    key: "{{ lookup('file', '{{ role_path }}/files/dsr-batch-{{ environment_name }}.pub') }}"
  when: dsr_batch_enabled

- name: Deploy Tuxedo services
  ansible.builtin.include_tasks: deploy.yml

- name: Find application-specific CloudWatch configuration files
  ansible.builtin.find:
    paths: "{{ cloudwatch_agent.config_dir }}"
    patterns: 'cloudwatch-config-*.json'
  register: cloudwatch_configs

- name: Add configuration for Tuxedo service group to CloudWatch agent
  ansible.builtin.command:
    cmd: "{{ cloudwatch_agent.path }} -a append-config -m ec2 -s -c file:{{ item.path }}"
  loop: "{{ cloudwatch_configs.files }}"
  changed_when: true
